### ISSUE TITLE
What is the data source？ 

### ISSUE THREAD

**Issue by cecini** [chinsaiki/s4#1]
And Does it support trade？

**Comment by chinsaiki** [comment]
数据源目前是通达信，读取本地日线、分钟线数据文件，需提前使用通达信下载数据。
读取api参考include/tdx目录，例子参考application/test_tdx_local.cpp

以后会加入抓取通达信实盘数据的api，不过可能要很久以后。

交易在没有其它开源下单API前，也不开源。
